---
title: "HW 4"
author: "SDS348 Spring 2021"
output:
  html_document: default
  pdf_document: default
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, fig.align = "center", warning = F, message = F, R.options=list(max.print=100))

# Edit the file starting below
```

## Name: Santhosh Saravanan
## EID: sks3648

**This homework is due on Mar 8, 2021 at 8am. Submit a pdf file on Gradescope.**

*For all questions, include the R commands/functions that you used to find your answer (show R chunk). Answers without supporting code will not receive credit. Write full sentences to describe your findings.*

------------------------------------------------------------------------

### Question 1: (9 pts)

#### The dataset `world_bank_pop` is a built-in dataset in `tidyverse`. It contains information about total population and population growth, overall and more specifically in urban areas, for countries around the world.

##### 1.1 (1 pt) Save the dataset `world_bank_pop` as `myworld` and take a look at it with `head()`. Is the data tidy? Why or why not?

```{r}
library(tidyverse)
myworld <- world_bank_pop
head(myworld)
```

*Each country abbreviation forms a row with information stemming from the indicator and year. Each variable (indicator, year, and country code) all form a distinct column. Hence, the data is tidy.*


##### 1.2 (1 pt) Using pipes and `dplyr` functions, how many countries are there in the dataset?

```{r}
# your code goes here (make sure to add comments)
myworld %>%
  summarise(count=n_distinct(country))
#first we group by country and use count parameter in summarise dplyr method 
```

*There are 264 countries in the dataset.*


##### 1.3 (2 pts) Use one of the `pivot` functions to create a new dataset, `myworld2`, with the years 2000 to 2017 appearing as a [numeric]{.ul} variable **`year`**, and the different values for the indicator variable are in a variable called **`value`**. In this new dataset, how many lines are there per country? Why does it make sense?

```{r}
# your code goes here (make sure to add comments)
myworld2 <- myworld %>% pivot_longer(-c(country,indicator), names_to = "year", names_transform = list(year= as.integer))
head(myworld2)
myworld2%>%count(country,indicator,sort = TRUE) # find the number of times a country is used for every type of indicator
myworld2%>%count(country,sort = TRUE) # just to confirm that the total number of rows 
# for every country is 72.
```

*There are about 72 lines per country. This makes sense because there are 4 indicators: population growth, total population, urban population growth, and total urban population. Given that the years range from 2000 to 2017, that's about 17 years. 18 years per indicator gives about 72 measurements per country, so it makes sense.*


##### 1.4 (3 pts) Represent the total population growth and urban population growth in the world (country code is `WLD`) between 2000 and 2017. How has population growth changed over the years?

```{r}
# your code goes here (make sure to add comments)
myworld2%>% filter(country=="WLD" & indicator == "SP.URB.GROW")
ggplot(myworld2%>% filter(country=="WLD" & indicator == "SP.URB.GROW"),aes(x= `year`, y= `value`)) + geom_point(size=1.5,color="Blue") + geom_line() + labs(y="Urban population growth",x="Year") + ggtitle("Urban Population Growth by Year in World")
ggplot(myworld2%>% filter(country=="WLD" & indicator == "SP.POP.GROW"),aes(x= `year`, y= `value`)) + geom_point(size=1.5,color="Blue") + geom_line() + labs(y="Total population growth",x="Year") + ggtitle("Total Population Growth by Year in World")
```

*Urban population growth reached its peak above 2.3 at around 2002-2003 and has declined ever since until past 2005. After 2005, there was a momentary spike upward at around 2007-2007 but has declined until experiencing a sharp decline after 2010. Ever since, the rate of decrease is still present, but a lot slower after 2011.* 
*For total population growth, it's been steadily decreasing till a a short while after 2010. There was an all-time low at the time at 2011, but it steadily gre back and has similarily, the rate of decrease is still present, but it's a bit higher than the urban population growth after 2011. *


##### 1.5 (2 pts) Use one of the `pivot` functions to create a new dataset, `myworld3`, with the different categories for the indicator variable appearing as their own variables. Use `dplyr` functions to rename `SP.POP.GROW` and `SP.URB.GROW`, as `pop_growth` and `pop_urb_growth` respectively. What is the country code that had the highest population growth in 2017?

```{r}
myworld3 <- myworld2 %>% pivot_wider( names_from= indicator,values_from= value)
myworld3 <- myworld3 %>% rename(pop_growth = SP.POP.GROW, pop_urb_growth = SP.URB.GROW)
myworld3 %>% filter(year==2017) %>% arrange(desc(pop_growth))
```

*OMN has the highest population growth in 2017.*


### Question 2: (10 pts)

#### From answering the previous question, we have no idea what actual countries are represented by the codes. We will now use a package that has information about the coding system used by the World bank.

##### 2.1 (2 pts) Install the package `countrycode`. We will use a built-in dataset called `codelist`. Make sure to upload the library and save this dataset as `mycodes`. Using `dplyr` functions, modify `mycodes` to: 1. select only the variables continent, `wb` (World Bank code), and `country.name.en` (country name in English); 2. filter to keep countries in Europe only; 3. remove countries with missing `wb` code. How many countries are there in Europe with a World Bank code?

```{r}
#install.packages("countrycode")

library(countrycode)

mycodes <- codelist
mycodes <- mycodes %>% select(continent, wb, country.name.en) %>% filter(continent == "Europe") %>% drop_na(wb) # select countries based on continent, wb, and country name in English
# filter with continent == "Europe" and drop_na values in wb column
nrow(mycodes)
# your code goes here (make sure to add comments)
```

*There are 46 countries in Europe with a World Bank Code.*


##### 2.2 (2 pts) Use a `left_join()` function to create a new dataset, `myeurope`, to add data to the countries in `mycodes` dataset from `myworld3` dataset. Match the two datasets based on the World Bank code. Using `dplyr` functions, change the name of the variable containing the World Bank code to `country`.

```{r}
# your code goes here (make sure to add comments)
mycodes <- rename(mycodes,c("country" = "wb"))
myeurope <- mycodes %>%
left_join(myworld3, by= c("country"))
```


##### 2.3 (1 pt) Using `dplyr` functions, what was the total population in European countries in 2017? Give your answer in million (round to the next million).

```{r}
  myeurope1 <- myeurope %>% filter(continent == 'Europe' & year == 2017)
  sum(myeurope1$SP.POP.TOTL)
```

*There are 744 million people in Europe in 2017.*


##### 2.4 (2 pts) Represent the annual total population in European countries between 2000 and 2017. Express the total population in million. How has European population changed over the years?

```{r}
annualNumbers = myeurope %>% group_by(year) %>% summarise(totalPop=sum(SP.POP.TOTL)/1000000)
ggplot(annualNumbers,aes(x= `year`, y=totalPop )) + geom_point(size=1.5,color="Blue") + geom_line() + labs(y="Total annual population (million)",x="Year") + ggtitle("Total Annual Population by Year in Europe")
```

*Population seems to be strictly increasing except for 2011, where there was a slight dip. After 2011, it seems to continue to increase.*


##### 2.5 (2 pts) Create a new dataset `myeurope2017` by filtering the data for the `year` 2017, dropping the variable `year`, and creating a new variable `prop_urb` which is the proportion of urban population for each country. Which European country had the lowest proportion of urban population in 2017?

```{r}
myeurope2017 <- myeurope %>%filter(year == 2017)%>% select(-year) %>% mutate(prop_urb = SP.URB.TOTL/SP.POP.TOTL) %>% arrange(prop_urb)
myeurope2017
```

*Liechtenstein had the lowest proportion of urban population in 2017*


##### 2.6 (1 pt) Using `dplyr` functions, find the top 3 countries in terms of their total population in 2017.

```{r}
topmyeurope <- myeurope %>%filter(year==2017)
arrange(topmyeurope,desc(SP.POP.TOTL))
```

*Russia, Germany, and France are the top 3 countries in terms of total population in 2017*


### Question 3: (6 pts)

#### When dealing with location data, we can actually visualize information on a map if we have geographic information such as latitude and longitude.

##### 3.1 (1 pt) We will use a built-in function called `map_data()` to get geographic coordinates about countries in the world (see below). Take a look at the dataset `mapWorld` with `glimpse()`. What variable could we use to join this dataset with `myeurope2017` dataset?

```{r}
# geographic coordinates about countries in the world
mapWorld <- map_data("world")
glimpse(mapWorld)
```

*We could use the region variable to join the dataset with the myeurope2017 dataset.*


##### 3.2 (1 pt) We want to use a `left_join()` function to create a new dataset, `mymap`, to add data to the countries in `myeurope2017` dataset from `mapWorld` dataset, matching the two datasets based on the country name. If we then use `dplyr` functions, we can identify some missing values for `lat` and `long` in the new dataset. Indeed, some countries such as United Kingdom did not have a match. Why do you think this happened?

```{r}
myeurope2017 <- rename(myeurope2017,c("region" = "country.name.en"))
mymap <- myeurope2017 %>%
left_join(mapWorld, by= c("region"))
```

*Your answer goes here. 1-2 sentences.*


##### 3.3 (1 pt) To identify all countries that did not have an exact match, do an `anti_join()` and display only distinct country names. How many countries did not have an exact match? *Note: using anti_join() is a very usedul function to identify differences between datasets.*

```{r}
# your code goes here (make sure to add comments)
```

*Your answer goes here. 1-2 sentences.*


##### 3.4 (1 pt) Joining datasets by variables containing names often leads to a mismatch because spelling can vary from one dataset to another. Sometimes we need to manually fix spelling in order to be able to match values. Consider the code given below. Replace the name of United Kingdom so that its name in `myeurope2017` dataset corresponds to the name given in `mapWorld` dataset. Following this code, add a pipe and use a `left_join()` function to create the new dataset, `mymap`, adding data to the countries in `myeurope` dataset from `mapWorld` dataset.

```{r}
# mymap <- myeurope2017 %>%
#   mutate(country_clean = recode(country.name.en,
#                                'United Kingdom' = '???',
#                                'Bosnia & Herzegovina' = 'Bosnia and Herzegovina',
#                                'Czechia' = 'Czech Republic',
#                                'North Macedonia' = 'Macedonia')) # continue code here %>%
```

##### 3.5 (2 pts) Let's visualize how population growth varies across European countries. Install the package `ggmap`, call the corresponding library, and use the R code provided below. Try to identify what each component of the graph does by completing the code with comments.

```{r}
# install.packages("ggmap")
# library(ggmap)
# 
# mymap %>%
#   ggplot(aes(x=long, y=lat, group = group, fill = pop_growth)) + 
#   # comment next line
#   geom_polygon(colour = "black") +
#   # comment next line
#   scale_fill_gradient(low = "white", high = "blue", guide="colorbar") +
#   # comment next line
#   labs(fill = "Growth", title = "Population Growth in 2017", x="Longitude", y="Latitude") +
#   # comment next line
#   xlim(-25,50) + ylim(35,70)
```

------------------------------------------------------------------------

```{r, echo=F}
## DO NOT DELETE THIS BLOCK!
Sys.info()
```
